# Generated by Django 5.0.6 on 2024-06-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_transacao_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='id_banco',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
